var tree = [["Squeeze1_0","Squeeze1_0.html","",
                [["Api","Squeeze1_0\/Api.html","",
                [["Comment","Squeeze1_0\/Api\/Comment.html","",
                [        ]],["DashboardWidget","Squeeze1_0\/Api\/DashboardWidget.html","",
                [        ]],["Menu","Squeeze1_0\/Api\/Menu.html","",
                [        ]],["Options","Squeeze1_0\/Api\/Options.html","",
                [        ]],["Post","Squeeze1_0\/Api\/Post.html","",
                [        ]],["SettingsField","Squeeze1_0\/Api\/SettingsField.html","",
                [        ]],["SettingsSection","Squeeze1_0\/Api\/SettingsSection.html","",
                [        ]],["User","Squeeze1_0\/Api\/User.html"," < WP_User",
                [        ]]        ]],["Controller","Squeeze1_0\/Controller.html","",
                [["AdminPageController","Squeeze1_0\/Controller\/AdminPageController.html","",
                [        ]],["DashboardWidget","Squeeze1_0\/Controller\/DashboardWidget.html","",
                [        ]],["PageController","Squeeze1_0\/Controller\/PageController.html","",
                [        ]],["WidgetController","Squeeze1_0\/Controller\/WidgetController.html","",
                [        ]]        ]],["Db","Squeeze1_0\/Db.html","",
                [["Config","Squeeze1_0\/Db\/Config.html","",
                [        ]],["PDO","Squeeze1_0\/Db\/PDO.html"," < PDO",
                [        ]],["PDOStatement","Squeeze1_0\/Db\/PDOStatement.html"," < PDOStatement",
                [        ]]        ]],["Implementable","Squeeze1_0\/Implementable.html","",
                [["iApi","Squeeze1_0\/Implementable\/iApi.html","",
                [        ]],["iController","Squeeze1_0\/Implementable\/iController.html","",
                [        ]],["iWidget","Squeeze1_0\/Implementable\/iWidget.html","",
                [        ]]        ]],["PostType","Squeeze1_0\/PostType.html","",
                [["MetaBox","Squeeze1_0\/PostType\/MetaBox.html","",
                [["MetaBox","Squeeze1_0\/PostType\/MetaBox\/MetaBox.html","",
                [        ]]        ]],["PostType","Squeeze1_0\/PostType\/PostType.html","",
                [        ]]        ]],["Util","Squeeze1_0\/Util.html","",
                [["Date","Squeeze1_0\/Util\/Date.html","",
                [        ]],["String","Squeeze1_0\/Util\/String.html","",
                [        ]]        ]],["Widget","Squeeze1_0\/Widget.html","",
                [["Widget","Squeeze1_0\/Widget\/Widget.html"," < WP_Widget",
                [        ]]        ]],["Activation","Squeeze1_0\/Activation.html","",
                [        ]],["Bootstrapper","Squeeze1_0\/Bootstrapper.html","",
                [        ]],["Deactivation","Squeeze1_0\/Deactivation.html","",
                [        ]],["Exception","Squeeze1_0\/Exception.html"," < Exception",
                [        ]],["Mustache","Squeeze1_0\/Mustache.html"," < Mustache_Engine",
                [        ]],["SplClassLoader","Squeeze1_0\/SplClassLoader.html","",
                [        ]],["Vendor","Squeeze1_0\/Vendor.html","",
                [        ]]        ]]        ]

